# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-10 18:16
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Pembelian', 'verbose_name_plural': 'Pembelian'},
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.FileField(blank=True, max_length=300, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=b'/media//files', location=b'/Users/ardzix/Documents/LandInstallmentApp/project/media/files'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='finance',
            name='content_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
